import {Roboto} from 'next/font/google'
import { Hero } from "app/components/home/Hero"
import { Description } from 'app/components/home/Description';  
import { Header } from "app/components/Shared/Header";
import { Footer } from "app/components/Shared/Footer";
import 'app/sass/globals.sass'

/*export const metadata: Metadata = {
  title: "Mi Tienda",
  description: "Generated by create next app",
};*/

const roboto = Roboto({
  weight: ["100", "300", "500", "700"],
  subsets: ["latin"]

})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (

    <html lang="en">
  
      <body className={roboto.className}>
        
        <Header />
        <Hero />
        <Description />

        {children}

        <Footer />

      </body>
    </html>
  );
}
