
import { Geist, Geist_Mono } from "next/font/google";

import { Header } from "app/components/Shared/Header";

import { Footer } from "app/components/Shared/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/*export const metadata: Metadata = {
  title: "Mi Tienda",
  description: "Generated by create next app",
};*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
  
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        
        <Header />

        {children}

        <Footer />

      </body>
    </html>
  );
}
